CREATE DATABASE RECU;

USE RECU;

CREATE TABLE CLIENTES (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(150) NOT NULL,
TELEFONE VARCHAR(22) NOT NULL,
EMAIL VARCHAR (155) NOT NULL
);

INSERT INTO CLIENTES (NOME, TELEFONE, EMAIL) VALUES
("Gabriel", "(71) 95524-4545", "gabriel@gmail.com"),
("Vanessa", "(71) 65552-9998", "vanessa@gmail.com");

CREATE TABLE CONTAS_BANCARIAS (
NUMERO_CONTA INT PRIMARY KEY,
AGENCIA VARCHAR(5) NOT NULL,
ID INT,
TIPO_CONTA VARCHAR (10) NOT NULL,
SALDO DECIMAL (10,2) NOT NULL,
FOREIGN KEY (ID) REFERENCES CLIENTES(ID) 
);

INSERT INTO CONTAS_BANCARIAS (NUMERO_CONTA, AGENCIA, ID, TIPO_CONTA, SALDO) VALUES
('00021', "3554", '1', "Corrente", 1500.00),
('00039', "8966", '2', "Poupança", 2600.00);

SELECT CLIENTES.NOME, CONTAS_BANCARIAS.SALDO
FROM CLIENTES
INNER JOIN CONTAS_BANCARIAS ON CLIENTES.ID = CONTAS_BANCARIAS.ID;

DELETE FROM CONTAS_BANCARIAS WHERE NUMERO_CONTA = 00021;

SELECT NUMERO_CONTA FROM CONTAS_BANCARIAS;

UPDATE CONTAS_BANCARIAS SET NUMERO_CONTA = 00458 WHERE ID = 2;

