CREATE DATABASE PRATICA;

USE PRATICA;

CREATE TABLE FILME (
ID_FILME INT PRIMARY KEY AUTO_INCREMENT,
TITULO VARCHAR (155) NOT NULL,
ANO_LANCAMENTO INT NOT NULL,
DIRETOR VARCHAR (155) NOT NULL
);

INSERT INTO FILME (ID_FILME, TITULO, ANO_LANCAMENTO, DIRETOR) VALUES
('1', "Crepúsculo", '2008', "Catherine Hardwicke"),
('2', "Jogos Vorazes", '2012', "Gary Ross"),
('3', "Maze Runner", '2014', "Wes Ball");

DELETE FROM FILME WHERE ID_FILME = 2;

UPDATE FILME SET ANO_LANCAMENTO = '2015' WHERE ID_FILME = 3;

SELECT * FROM FILME;

DROP TABLE FILME;

-- VIEWS --

CREATE VIEW TESTE AS
SELECT TITULO, ANO_LANCAMENTO
FROM FILME
WHERE ANO_LANCAMENTO > 2010;

DROP VIEW TESTE;

SELECT * FROM TESTE;

-- FIM VIEWS --


