CREATE TABLE PRODUTOS (
ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(155) NOT NULL,
PRECO_UNICO DECIMAL(10, 2) NOT NULL,
CATEGORIA VARCHAR(155) NOT NULL
);

INSERT INTO PRODUTOS (NOME, PRECO_UNICO, CATEGORIA) VALUES
("Banana", 6.99, "Alimento"),
("Celular", 2999.99, "Eletronico"),
("Blusa", 19.99, "Roupa"),
("Açucar", 3.99, "Alimento");

CREATE TABLE ESTOQUE (
ID_PRODUTO INT,
QUANT INT NOT NULL,
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

INSERT INTO ESTOQUE (ID_PRODUTO, QUANT) VALUES
('1', "85"),
('2', "13"),
('3', "26"),
('4', "150");

CREATE VIEW ESTOQUE_CRITICO AS
SELECT PRODUTOS.NOME AS NOME_PRODUTO, ESTOQUE.QUANT
FROM PRODUTOS
JOIN ESTOQUE ON PRODUTOS.ID_PRODUTO = ESTOQUE.ID_PRODUTO 
WHERE ESTOQUE.QUANT < 50; 

SELECT * FROM ESTOQUE_CRITICO;